name = "MLPPCVE"
uuid = "8a8936cc-42e3-4d2a-879e-815b3b2da5cd"
authors = ["jeffersonfparil <jeffersonparil@gmail.com>"]
version = "0.1.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
CUDA = "5.8.3"
LinearAlgebra = "1.11.0"
Random = "1.11.0"
julia = "1.11"

[extras]
CUDA_Runtime_jll = "76a88914-d11a-5bdc-97e0-2f5a05c973a2"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[apps]
MLPPCVE = {Multi-layer perceptrons for phenotype and covariance estimation. Notes: (1) currently cannot compile via JuliaC because of errors on CUDA.jl. (2) Planning to implement on Zig. Why not Rust? I would like to have more control and less hidden magic.}